/**
 * Headcount Agent — Response Library
 *
 * Handles: Open reqs, fill rate analysis, salary budget, workforce planning,
 * backfill decisions, headcount movement, and retention risk.
 */

import type { AgentResponse } from "@/types/finance";
import type { ConversationContext } from "../agentEngine";

type Route = {
  key: string;
  keywords: string[];
  negatives?: string[];
  weight: number;
  handler: (ctx: ConversationContext) => AgentResponse;
};

export const headcountResponses: Route[] = [

  // ── 1. Open requisitions ───────────────────────────────────────────────────
  {
    key: "open-reqs",
    keywords: [
      "open req", "open position", "open role", "vacancy", "unfilled",
      "how many open", "open headcount", "open hc", "open jobs",
    ],
    weight: 9,
    handler({ snapshot: s }) {
      const { fmt, dt } = s;
      const openByBU = s.hcByBU.filter(b => b.open > 0).sort((a, b) => b.open - a.open);
      return {
        answer: `**Open Requisitions Report — ${s.periodLabel}**

**Summary**: ${s.hcSummary.open} open positions + ${s.hcSummary.pendingOffer} pending offers across ${openByBU.length} business units.

**Open Reqs by Business Unit**
${openByBU.map(b => {
  const avgSalary = b.salaryBudget / b.total;
  const openSalaryCost = avgSalary * b.open;
  return `**${b.bu}** — ${b.open} open position${b.open > 1 ? "s" : ""}
   Fill rate: ${b.filled}/${b.total} (${((b.filled / b.total) * 100).toFixed(0)}%)
   Avg salary for open reqs: ~${fmt(avgSalary, true)}
   Annual salary at risk: ~${fmt(openSalaryCost, true)}`;
}).join("\n\n")}

**Individual Open Requisitions**
${s.openReqs.map((h, i) => `${i + 1}. **${h.title}** (${h.level})
   BU: ${h.businessUnit} | Location: ${h.location}
   ${h.isBackfill ? "🔄 Backfill role" : "🆕 New headcount"}
   Open since: ${h.openDate ? dt(h.openDate) : "Unknown"}
   Annual salary: ${fmt(h.annualSalary, true)}`).join("\n\n")}

**Open Req Impact Analysis**
- Salary savings generated by open reqs YTD: ~${fmt(s.openReqSalaryAtRisk * 0.42)}
- Incremental contractor cost to backfill (estimated): ~${fmt(s.hcSummary.open * 17_000 * 5)}
- Net cost of vacancy (contractor premium above FTE): ~${fmt(s.hcSummary.open * 17_000 * 5 - s.openReqSalaryAtRisk * 0.42)}

**Priority Hires (by risk to operations)**
1. IAM Architect (Security) — security posture gap; contractor covering at 38% premium
2. Data Engineer II + Analytics Engineer (Data & Analytics) — team operating at capacity
3. FinOps Analyst (Cloud Engineering) — this hire directly reduces cloud overspend`,
        keyPoints: [
          `${s.hcSummary.open} open reqs generating ~${fmt(s.openReqSalaryAtRisk * 0.42)} in YTD salary savings`,
          `Contractor backfill cost exceeds savings by ~${fmt(s.hcSummary.open * 17_000 * 5 - s.openReqSalaryAtRisk * 0.42)} — net negative`,
          "IAM Architect vacancy = highest operational risk (security coverage gap)",
          "FinOps Analyst = highest financial ROI hire (directly reduces $350K cloud overrun)",
          `${s.hcSummary.pendingOffer} positions at offer stage — forecast ${Math.ceil(s.hcSummary.pendingOffer * 0.8)} offers to close`,
        ],
        riskFlags: [],
        actions: [
          { id: "HC-OR1", priority: "High", title: "Accelerate IAM Architect pipeline", description: "Security gap critical — target offer by July 15", owner: "Talent Acquisition + Security", dueDate: "2026-07-15" },
          { id: "HC-OR2", priority: "High", title: "Hire FinOps Analyst by Q3", description: "Direct ROI: this hire manages $350K cloud savings program", owner: "TA + Cloud Engineering", dueDate: "2026-07-31" },
          { id: "HC-OR3", priority: "Medium", title: "Data Engineering team — close 2 open reqs", description: "Team at capacity — delay risks data platform delivery timelines", owner: "TA + Data Engineering", dueDate: "2026-08-31" },
        ],
      };
    },
  },

  // ── 2. Fill rate & headcount summary ──────────────────────────────────────
  {
    key: "fill-rate",
    keywords: [
      "fill rate", "filled", "how many people", "total headcount", "hc summary",
      "headcount summary", "how many employees", "team size", "staffing level",
    ],
    weight: 8,
    handler({ snapshot: s }) {
      const { fmt } = s;
      return {
        answer: `**Headcount Summary & Fill Rate — ${s.periodLabel}**

**Overall Headcount**
| Status | Count | % of Total |
|---|---|---|
| Filled | **${s.hcSummary.filled}** | ${((s.hcSummary.filled / s.hcSummary.total) * 100).toFixed(0)}% |
| Open | ${s.hcSummary.open} | ${((s.hcSummary.open / s.hcSummary.total) * 100).toFixed(0)}% |
| Pending Offer | ${s.hcSummary.pendingOffer} | ${((s.hcSummary.pendingOffer / s.hcSummary.total) * 100).toFixed(0)}% |
| On Leave | ${s.hcSummary.onLeave} | ${((s.hcSummary.onLeave / s.hcSummary.total) * 100).toFixed(0)}% |
| **Total Approved** | **${s.hcSummary.total}** | 100% |

**Fill Rate: ${(s.fillRate * 100).toFixed(1)}%** (vs. target of 90%)

**Fill Rate by Business Unit**
${s.hcByBU.sort((a, b) => (b.filled / b.total) - (a.filled / a.total)).map(b => {
  const rate = ((b.filled / b.total) * 100).toFixed(0);
  const indicator = parseInt(rate) >= 90 ? "🟢" : parseInt(rate) >= 75 ? "🟡" : "🔴";
  return `${indicator} **${b.bu}**: ${rate}% (${b.filled}/${b.total} filled, ${b.open} open)`;
}).join("\n")}

**Salary Budget Context**
- Annual salary budget (all positions): ${fmt(s.salaryBudget)}
- Projected salary spend (filled positions): ~${fmt(s.salaryBudget * s.fillRate * 0.95)}
- Salary savings from open reqs (H1): ~${fmt(s.salaryBudget * (1 - s.fillRate) * 0.45)}

**Trend**
Fill rate has held steady at ${(s.fillRate * 100).toFixed(0)}% over the past 3 months. With ${s.hcSummary.pendingOffer} offers outstanding and an expected 80% acceptance rate, fill rate is projected to reach ${((( s.hcSummary.filled + Math.round(s.hcSummary.pendingOffer * 0.8)) / s.hcSummary.total) * 100).toFixed(0)}% by Q3.`,
        keyPoints: [
          `Overall fill rate: ${(s.fillRate * 100).toFixed(1)}% — ${s.hcSummary.open} open, ${s.hcSummary.pendingOffer} at offer stage`,
          `${s.hcByBU.filter(b => b.filled / b.total >= 0.9).length} BUs at or above 90% fill rate target`,
          `${s.hcByBU.filter(b => b.filled / b.total < 0.8).length} BUs below 80% fill rate — Cloud Engineering and Data & Analytics at risk`,
          `Salary savings from open reqs: ~${fmt(s.salaryBudget * (1 - s.fillRate) * 0.45)} — partially offsets contractor overages`,
          `Projected Q3 fill rate: ${((( s.hcSummary.filled + Math.round(s.hcSummary.pendingOffer * 0.8)) / s.hcSummary.total) * 100).toFixed(0)}% if all pending offers close`,
        ],
        riskFlags: [],
        actions: [
          { id: "HC-FR1", priority: "Medium", title: "Q3 fill rate target: 88%", description: `Close ${s.hcSummary.open - 2} of ${s.hcSummary.open} open reqs by September — set milestone plan`, owner: "Talent Acquisition + HR", dueDate: "2026-07-01" },
        ],
      };
    },
  },

  // ── 3. Salary budget / cost analysis ──────────────────────────────────────
  {
    key: "salary-budget",
    keywords: [
      "salary", "compensation", "pay", "cost per head", "labor cost",
      "salary budget", "total comp", "how much does headcount cost",
    ],
    weight: 8,
    handler({ snapshot: s }) {
      const { fmt } = s;
      const avgSalary = s.salaryBudget / s.hcSummary.total;
      const filledSalary = s.salaryBudget * (s.hcSummary.filled / s.hcSummary.total);
      const benefitsLoad = 0.27;
      const totalLabor = filledSalary * (1 + benefitsLoad);
      return {
        answer: `**Salary Budget & Labor Cost Analysis — ${s.periodLabel}**

**Approved Headcount Budget**
- Total annual salary budget: **${fmt(s.salaryBudget)}**
- Active salary cost (filled positions): ~**${fmt(filledSalary)}**
- Benefits load (27%): ${fmt(filledSalary * benefitsLoad)}
- **Total annual FTE labor cost (salary + benefits): ${fmt(totalLabor)}**

**Metrics**
- Average salary (all approved positions): ${fmt(avgSalary)}
- Cost per FTE (salary + benefits): ${fmt(avgSalary * (1 + benefitsLoad))}

**By Level — Average Compensation**
| Level | Count | Est. Avg. Salary |
|---|---|---|
| VP | ${s.headcount.filter(h => h.level === "VP").length} | ${fmt(272_000)} |
| Director | ${s.headcount.filter(h => h.level === "Dir").length} | ${fmt(213_000)} |
| M1/M2/M3 | ${s.headcount.filter(h => (["M1","M2","M3"] as string[]).includes(h.level)).length} | ${fmt(181_000)} |
| IC5 (Sr. Principal) | ${s.headcount.filter(h => h.level === "IC5").length} | ${fmt(188_000)} |
| IC4 (Senior) | ${s.headcount.filter(h => h.level === "IC4").length} | ${fmt(160_000)} |
| IC3 (Mid-Level) | ${s.headcount.filter(h => h.level === "IC3").length} | ${fmt(109_000)} |

**Open Req Salary at Risk**
${s.openReqs.map(h => `- ${h.title} (${h.level}): ${fmt(h.annualSalary)}`).join("\n")}
**Total open req salary: ${fmt(s.openReqs.reduce((sum, h) => sum + h.annualSalary, 0))}**

**Budget vs. Projected Spend**
YTD salary savings from open positions: ~${fmt(s.openReqSalaryAtRisk * 0.42)}
Projected full-year salary spend: ~${fmt(filledSalary * 0.97)} (slight attrition assumed)
Salary budget variance (favorable): ~${fmt(s.salaryBudget - filledSalary * 0.97)}`,
        keyPoints: [
          `Total annual salary budget: ${fmt(s.salaryBudget)} | With benefits (27% load): ${fmt(totalLabor)}`,
          `Average salary across all levels: ${fmt(avgSalary)} | Cost per FTE (fully loaded): ${fmt(avgSalary * 1.27)}`,
          `Open reqs represent ${fmt(s.openReqs.reduce((s, h) => s + h.annualSalary, 0))} in annual salary budget — generating savings while vacant`,
          "VP and Director compensation drives disproportionate budget concentration",
          `Full-year salary favorable variance: ~${fmt(s.salaryBudget - filledSalary * 0.97)} — partially offsets cloud overruns`,
        ],
        riskFlags: [],
        actions: [
          { id: "HC-SB1", priority: "Low", title: "Include open req savings in Q2 forecast offset", description: "Coordinate with FP&A — open HC savings should reduce net IT forecast variance", owner: "IT Finance + FP&A", dueDate: "2026-07-01" },
        ],
      };
    },
  },

  // ── 4. Backfills & headcount movement ─────────────────────────────────────
  {
    key: "backfill",
    keywords: [
      "backfill", "replacement", "attrition", "turnover", "who left",
      "departures", "movement", "headcount change", "new hire", "recent hire",
    ],
    weight: 8,
    handler({ snapshot: s }) {
      const { fmt } = s;
      const backfills = s.headcount.filter(h => h.isBackfill);
      return {
        answer: `**Headcount Movement & Backfill Analysis — ${s.periodLabel}**

**Backfill Positions**
${backfills.length} of ${s.hcSummary.total} approved positions are backfills (replacing departed employees):

${backfills.map(h => `- **${h.title}** (${h.businessUnit}) | ${h.status} | ${fmt(h.annualSalary)}/year`).join("\n")}

**Backfill Rate**: ${((backfills.length / s.hcSummary.total) * 100).toFixed(0)}% of approved headcount
**Industry Benchmark**: 15–20% backfill rate is typical for IT organizations

**Cost of Backfill**
Each backfill position represents:
- Recruitment cost: ~${fmt(25_000)} (recruiter fees or internal RPO cost)
- Onboarding & productivity ramp: ~${fmt(18_000)} (3–6 months at 60% productivity)
- Knowledge transfer risk: Medium to high depending on role seniority
- **Total cost of one backfill (average): ~${fmt(43_000)}**

**Total Backfill Investment This Year**: ~${fmt(backfills.length * 43_000)}

**Retention Risk Assessment**
Current on-leave employee (Sr. Enterprise Architect, EA team) has been out since before January. A backfill decision should be made if the leave extends beyond Q2. The contractor covering this role (Carlos Mendoza) is already over budget.

**Headcount Movement Since Q1**
- New hires (YTD): Estimated 3 positions filled since January
- Backfills opened (YTD): ${backfills.filter(h => h.status === "Open").length} currently open backfills
- Offers outstanding: ${s.hcSummary.pendingOffer}`,
        keyPoints: [
          `${backfills.length} backfill positions — ${((backfills.length / s.hcSummary.total) * 100).toFixed(0)}% backfill rate (within normal range)`,
          `Average cost per backfill: ~$43K (recruitment + ramp) — total investment: ~${fmt(backfills.length * 43_000)}`,
          "Sr. Enterprise Architect on leave — contractor covering at $160K YTD; backfill decision needed",
          `${backfills.filter(h => h.status === "Open").length} open backfill positions currently in recruiting pipeline`,
          "Retention investment in current team reduces backfill rate and total cost",
        ],
        riskFlags: [],
        actions: [
          { id: "HC-BF1", priority: "Medium", title: "Backfill decision: Sr. Enterprise Architect", description: "Employee on leave since Q1 — formal return-or-backfill decision needed with HR/Legal", owner: "HR + EA Director", dueDate: "2026-07-01" },
        ],
      };
    },
  },

  // ── 5. Default ────────────────────────────────────────────────────────────
  {
    key: "default",
    keywords: [],
    weight: 0,
    handler({ snapshot: s }) {
      const { fmt } = s;
      return {
        answer: `**Headcount Agent — Ready to Help**

I analyze workforce data, open requisitions, and salary budgeting. Current snapshot:

- **Total positions**: ${s.hcSummary.total} approved
- **Filled**: ${s.hcSummary.filled} (${(s.fillRate * 100).toFixed(0)}% fill rate)
- **Open reqs**: ${s.hcSummary.open} | **Pending offers**: ${s.hcSummary.pendingOffer}
- **Annual salary budget**: ${fmt(s.salaryBudget)}

**I can help you with:**
- Open requisition analysis and hiring priority recommendations
- Fill rate breakdown by business unit
- Salary budget tracking and open req financial impact
- Backfill decisions and headcount movement analysis

What would you like to explore?`,
        keyPoints: [
          `Fill rate: ${(s.fillRate * 100).toFixed(0)}% | ${s.hcSummary.open} open reqs | ${fmt(s.salaryBudget)} annual salary budget`,
          "Ask me about open reqs, fill rates, salary budgets, or backfill decisions",
        ],
        riskFlags: [],
        actions: [],
      };
    },
  },
];
