import type { RiskFlag } from "@/types/finance";
import { formatCurrency } from "@/lib/formatters";
import clsx from "clsx";

// ─── Severity config ──────────────────────────────────────────────────────────

const severityConfig = {
  critical: {
    border:  "border-l-red-500",
    dot:     "bg-red-500",
    icon:    "🔴",
    pill:    "bg-red-100 text-red-700 border border-red-200",
    label:   "Critical",
  },
  warning: {
    border:  "border-l-amber-400",
    dot:     "bg-amber-400",
    icon:    "🟡",
    pill:    "bg-amber-100 text-amber-700 border border-amber-200",
    label:   "Warning",
  },
  info: {
    border:  "border-l-blue-400",
    dot:     "bg-blue-400",
    icon:    "🔵",
    pill:    "bg-blue-100 text-blue-700 border border-blue-200",
    label:   "Info",
  },
};

// ─── Summary bar ─────────────────────────────────────────────────────────────

function SummaryBar({ flags }: { flags: RiskFlag[] }) {
  const critical = flags.filter(f => f.severity === "critical").length;
  const warning  = flags.filter(f => f.severity === "warning").length;
  const info     = flags.filter(f => f.severity === "info").length;

  return (
    <div className="flex items-center gap-2">
      {critical > 0 && (
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-red-100 text-red-700 border border-red-200 glow-red">
          🔴 {critical}
        </span>
      )}
      {warning > 0 && (
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-amber-100 text-amber-700 border border-amber-200">
          🟡 {warning}
        </span>
      )}
      {info > 0 && (
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-blue-100 text-blue-700 border border-blue-200">
          🔵 {info}
        </span>
      )}
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

interface RiskAlertsProps {
  flags: RiskFlag[];
  limit?: number;
}

export default function RiskAlerts({ flags, limit }: RiskAlertsProps) {
  const shown  = limit ? flags.slice(0, limit) : flags;
  const hidden = flags.length - shown.length;

  return (
    <div className="card overflow-hidden">
      {/* Header */}
      <div className="card-header flex items-center justify-between gap-3">
        <div>
          <h2 className="section-title">Risk Alerts</h2>
          <p className="text-[11px] text-slate-400 mt-0.5">
            {flags.length} active · auto-generated by risk engine
          </p>
        </div>
        <SummaryBar flags={flags} />
      </div>

      {/* Flags */}
      <div className="divide-y divide-slate-50">
        {shown.map((flag) => {
          const cfg = severityConfig[flag.severity];
          return (
            <div
              key={flag.id}
              className={clsx(
                "px-5 py-4 border-l-4 transition-colors hover:bg-slate-50/50",
                cfg.border
              )}
            >
              <div className="flex items-start gap-3">
                {/* Severity dot */}
                <div className={clsx("w-2 h-2 rounded-full mt-1.5 shrink-0", cfg.dot)} />

                <div className="flex-1 min-w-0">
                  {/* Header row */}
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <span className={clsx(
                      "text-[10px] font-bold px-1.5 py-0.5 rounded-md",
                      cfg.pill
                    )}>
                      {cfg.label.toUpperCase()}
                    </span>
                    <span className="text-[10px] text-slate-400 font-medium">{flag.category}</span>
                    <span className="text-[10px] text-slate-300">·</span>
                    <span className="text-[10px] text-slate-400 font-mono">{flag.id}</span>
                  </div>

                  {/* Title */}
                  <p className="text-sm font-semibold text-slate-800 leading-snug">
                    {flag.title}
                  </p>

                  {/* Description */}
                  <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">
                    {flag.description}
                  </p>
                </div>

                {/* Impact */}
                {flag.impact > 0 && (
                  <div className="shrink-0 text-right">
                    <p className="text-[9px] text-slate-400 font-medium uppercase tracking-wide">Impact</p>
                    <p className="text-sm font-black text-red-600">
                      {formatCurrency(flag.impact, true)}
                    </p>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Show more */}
      {hidden > 0 && (
        <div className="px-5 py-3 border-t border-slate-100 bg-slate-50/50">
          <p className="text-[11px] text-slate-400 text-center">
            +{hidden} more risk{hidden > 1 ? "s" : ""} · view all on the CFO Summary page
          </p>
        </div>
      )}
    </div>
  );
}
