import type { AgentDefinition } from "./types";

export const agentRegistry: AgentDefinition[] = [
  {
    id: "cfo",
    name: "CFO Agent",
    title: "Chief Financial Officer",
    description: "Synthesizes financial performance, creates executive commentary, and flags major risks and opportunities across the IT portfolio.",
    avatar: "🏦",
    color: "indigo",
    capabilities: ["Executive Summaries", "Risk Flagging", "Cost Optimization", "Board Narratives"],
    suggestedQuestions: [
      "Give me the executive financial summary for May 2026",
      "What are the top 3 financial risks I need to act on this month?",
      "How do we explain the budget variance to the board?",
      "Where are our biggest cost optimization opportunities for H2?",
    ],
  },
  {
    id: "fpa",
    name: "FP&A Agent",
    title: "Financial Planning & Analysis",
    description: "Explains budget vs. actuals, reviews forecast changes, and identifies variance drivers by cost center and business unit.",
    avatar: "📊",
    color: "blue",
    capabilities: ["Variance Analysis", "Forecast Review", "Budget vs. Actuals", "Trend Analysis"],
    suggestedQuestions: [
      "What are the main drivers of our YTD budget variance?",
      "Which cost centers are most over budget and why?",
      "How is our full-year forecast tracking vs. the approved plan?",
      "Walk me through the month-over-month spend trend Jan–May",
    ],
  },
  {
    id: "procurement",
    name: "Procurement Agent",
    title: "Vendor & Contract Management",
    description: "Reviews vendor spend, flags contracts near expiration, identifies spend concentration risks, and supports renewal strategy.",
    avatar: "📋",
    color: "purple",
    capabilities: ["Contract Tracking", "Spend Analysis", "Risk Assessment", "Renewal Strategy"],
    suggestedQuestions: [
      "Which contracts are expiring in the next 90 days?",
      "Where do we have vendor concentration risk?",
      "Which vendors should we prioritize for renewal negotiations?",
      "What is our total committed vendor spend for the year?",
    ],
  },
  {
    id: "external-labor",
    name: "External Labor Agent",
    title: "Contractor Spend Management",
    description: "Tracks contractor spend, reviews burn rate by cost center, flags over-budget engagements, and identifies SOW risks.",
    avatar: "👷",
    color: "amber",
    capabilities: ["Burn Rate Analysis", "SOW Review", "Budget Compliance", "Contractor Tracking"],
    suggestedQuestions: [
      "Which contractors are over their approved SOW budget?",
      "What is our YTD contractor spend vs. budget by business unit?",
      "Which contractor engagements are ending in the next 60 days?",
      "How much of our external labor over-spend can be recovered?",
    ],
  },
  {
    id: "headcount",
    name: "Headcount Agent",
    title: "Workforce Planning & Analytics",
    description: "Reviews open positions, tracks filled roles, explains headcount movement, and supports workforce cost analysis.",
    avatar: "👥",
    color: "emerald",
    capabilities: ["HC Tracking", "Open Req Analysis", "Salary Budgeting", "Workforce Planning"],
    suggestedQuestions: [
      "How many open requisitions do we have and where are they?",
      "What is our headcount fill rate vs. approved plan?",
      "Which business units have the largest HC gaps?",
      "How much salary budget are open reqs generating in savings?",
    ],
  },
  {
    id: "cio",
    name: "CIO Finance Partner",
    title: "IT Executive Finance Partner",
    description: "Summarizes IT spend, explains cloud/project/labor trends, and creates CIO-ready talking points for executive and board audiences.",
    avatar: "💡",
    color: "rose",
    capabilities: ["CIO Briefings", "Cloud Trends", "Strategic Narrative", "Board Readiness"],
    suggestedQuestions: [
      "Prepare a 5-point IT financial briefing for the executive team",
      "Give me CIO-ready talking points on cloud spend and ROI",
      "How do I explain the IT budget variance to the CEO?",
      "What is the full IT investment story for FY2026?",
    ],
  },
  {
    id: "finance-bp",
    name: "Finance Business Partner",
    title: "Business Unit Finance Advisor",
    description: "Translates financial data into operational context for business unit leaders — variance explanations, budget owner guidance, and BU-level commentary.",
    avatar: "🤝",
    color: "teal",
    capabilities: ["BU Commentary", "Budget Owner Guidance", "Variance Context", "Reforecast Support"],
    suggestedQuestions: [
      "Explain this month's variance to my business unit in plain language",
      "Which cost centers in my BU need attention this month?",
      "What does finance need from me to close the month?",
      "How does my BU compare to plan for the year?",
    ],
  },
  {
    id: "validation",
    name: "Data Quality Advisor",
    title: "Ingestion Validation Specialist",
    description: "Interprets validation results, prioritizes data errors by financial impact, and guides remediation before re-upload.",
    avatar: "✅",
    color: "slate",
    capabilities: ["Error Triage", "Remediation Guidance", "Data Quality Trends", "Field Mapping Help"],
    suggestedQuestions: [
      "What errors were found in my last upload and how do I fix them?",
      "Which validation errors will block my data from being processed?",
      "How do I fix the missing cost center IDs in my GL export?",
      "What percentage of my rows passed validation?",
    ],
  },
];

export function getAgent(id: string): AgentDefinition | undefined {
  return agentRegistry.find((a) => a.id === id);
}
